<?php
/**
 * Career Compass - Seed 50+ Careers into Database
 * Run once: http://localhost/career-counselling-application/backend/seed_careers.php
 */

require_once 'config/database.php';

$database = new Database();
$db = $database->getConnection();

$careers = [
    // ==================== SCIENCE STREAM ====================
    ["Software Engineer", "technology", "science", "Design, develop, and maintain software applications and systems.", "₹6,00,000 - ₹25,00,000", "High (22% by 2030)", ["Python", "JavaScript", "Problem Solving", "Git"], [["step" => 1, "title" => "Bachelor's Degree", "desc" => "B.Tech/B.E. in Computer Science or IT"], ["step" => 2, "title" => "Build Portfolio", "desc" => "Create projects on GitHub"], ["step" => 3, "title" => "Internships", "desc" => "Complete 1-2 tech internships"], ["step" => 4, "title" => "Technical Skills", "desc" => "Master frameworks, cloud platforms"], ["step" => 5, "title" => "Entry-Level Job", "desc" => "Apply for junior developer roles"]], "B.Tech/B.E. in CS/IT", ["coding", "software", "programming", "developer", "tech"]],

    ["Data Scientist", "technology", "science", "Analyze complex data sets to derive insights and build predictive models.", "₹8,00,000 - ₹22,00,000", "Very High (31% by 2030)", ["Python", "Statistics", "Machine Learning", "SQL"], [["step" => 1, "title" => "Education", "desc" => "B.Tech + M.Tech or M.Sc in Statistics/CS"], ["step" => 2, "title" => "Core Tools", "desc" => "Master Python, R, SQL, Tableau"], ["step" => 3, "title" => "ML Skills", "desc" => "Learn TensorFlow, PyTorch"], ["step" => 4, "title" => "Projects", "desc" => "Kaggle competitions and real-world projects"], ["step" => 5, "title" => "Industry Role", "desc" => "Start as data analyst, grow to data scientist"]], "B.Tech/M.Tech or M.Sc", ["data", "analytics", "machine learning", "AI"]],

    ["Cybersecurity Analyst", "technology", "science", "Protect organizations from cyber threats and security breaches.", "₹5,00,000 - ₹18,00,000", "Very High (33% by 2030)", ["Network Security", "Ethical Hacking", "Risk Assessment", "Compliance"], [["step" => 1, "title" => "Education", "desc" => "B.Tech in CS/IT or Cybersecurity"], ["step" => 2, "title" => "Certifications", "desc" => "CEH, CompTIA Security+, CISSP"], ["step" => 3, "title" => "Practice", "desc" => "HackTheBox, TryHackMe labs"], ["step" => 4, "title" => "Entry Role", "desc" => "Junior security analyst"], ["step" => 5, "title" => "Specialize", "desc" => "Pen testing, incident response"]], "B.Tech in CS/IT", ["security", "hacking", "cyber", "network"]],

    ["Doctor (MBBS)", "healthcare", "science", "Diagnose and treat illnesses, prescribe medications, and care for patients.", "₹8,00,000 - ₹30,00,000", "Stable", ["Medical Knowledge", "Diagnosis", "Patient Care", "Communication"], [["step" => 1, "title" => "NEET Exam", "desc" => "Clear NEET-UG entrance exam"], ["step" => 2, "title" => "MBBS Degree", "desc" => "5.5 years MBBS program"], ["step" => 3, "title" => "Internship", "desc" => "1 year mandatory internship"], ["step" => 4, "title" => "PG Specialization", "desc" => "MD/MS via NEET-PG"], ["step" => 5, "title" => "Practice", "desc" => "Hospital or private practice"]], "MBBS + MD/MS", ["doctor", "medical", "health", "hospital", "patient"]],

    ["Pharmacist", "healthcare", "science", "Dispense medications, advise patients, and ensure drug safety.", "₹3,00,000 - ₹8,00,000", "Moderate", ["Pharmacology", "Chemistry", "Patient Counseling", "Regulations"], [["step" => 1, "title" => "B.Pharm", "desc" => "4-year Bachelor of Pharmacy"], ["step" => 2, "title" => "Registration", "desc" => "Register with Pharmacy Council"], ["step" => 3, "title" => "Practice", "desc" => "Hospital or retail pharmacy"], ["step" => 4, "title" => "M.Pharm", "desc" => "Optional Master's for advanced roles"], ["step" => 5, "title" => "Specialize", "desc" => "Clinical pharmacy, R&D, or regulatory"]], "B.Pharm / M.Pharm", ["pharmacy", "medicine", "drugs", "health"]],

    ["Biotechnologist", "technology", "science", "Apply biological systems for developing products in healthcare, agriculture, and industry.", "₹4,00,000 - ₹12,00,000", "High", ["Molecular Biology", "Genetics", "Bioinformatics", "Lab Skills"], [["step" => 1, "title" => "B.Tech/B.Sc", "desc" => "Degree in Biotechnology"], ["step" => 2, "title" => "Lab Experience", "desc" => "Internships in biotech labs"], ["step" => 3, "title" => "M.Tech/M.Sc", "desc" => "Advanced degree recommended"], ["step" => 4, "title" => "Research", "desc" => "Publish papers, join R&D"], ["step" => 5, "title" => "Industry", "desc" => "Pharma, agri-tech, or biotech firms"]], "B.Tech/M.Tech in Biotech", ["biology", "genetics", "research", "lab"]],

    ["Mechanical Engineer", "engineering", "science", "Design, develop, and test mechanical devices, engines, and systems.", "₹4,00,000 - ₹15,00,000", "Moderate (7% by 2030)", ["CAD", "Thermodynamics", "Materials Science", "Problem Solving"], [["step" => 1, "title" => "B.Tech", "desc" => "B.Tech in Mechanical Engineering"], ["step" => 2, "title" => "Technical Skills", "desc" => "Master SolidWorks, AutoCAD"], ["step" => 3, "title" => "Internships", "desc" => "Manufacturing or design internships"], ["step" => 4, "title" => "GATE", "desc" => "Optional GATE for PSUs/M.Tech"], ["step" => 5, "title" => "Career", "desc" => "Core industry or R&D roles"]], "B.Tech in Mechanical", ["machines", "manufacturing", "design", "engine"]],

    ["Civil Engineer", "engineering", "science", "Plan, design, and oversee construction of infrastructure projects.", "₹4,00,000 - ₹14,00,000", "Moderate", ["Structural Analysis", "AutoCAD", "Project Management", "Surveying"], [["step" => 1, "title" => "B.Tech", "desc" => "B.Tech in Civil Engineering"], ["step" => 2, "title" => "Software", "desc" => "Learn AutoCAD, STAAD Pro, Revit"], ["step" => 3, "title" => "Site Experience", "desc" => "Construction site internships"], ["step" => 4, "title" => "Licensing", "desc" => "Optional GATE/PSU exams"], ["step" => 5, "title" => "Growth", "desc" => "Project manager or consultant"]], "B.Tech in Civil", ["construction", "building", "infrastructure", "structure"]],

    ["Electrical Engineer", "engineering", "science", "Design and develop electrical systems, power generation, and electronics.", "₹4,00,000 - ₹14,00,000", "Moderate", ["Circuit Design", "Power Systems", "MATLAB", "Control Systems"], [["step" => 1, "title" => "B.Tech", "desc" => "B.Tech in Electrical/EEE"], ["step" => 2, "title" => "Core Skills", "desc" => "Power systems, electronics, embedded"], ["step" => 3, "title" => "Internship", "desc" => "Power sector or electronics firms"], ["step" => 4, "title" => "GATE", "desc" => "GATE for PSU placement"], ["step" => 5, "title" => "Specialize", "desc" => "Power, VLSI, or renewable energy"]], "B.Tech in EE/EEE", ["electrical", "power", "circuits", "electronics"]],

    ["Registered Nurse", "healthcare", "science", "Provide patient care and support in hospitals and clinics.", "₹3,00,000 - ₹8,00,000", "High", ["Patient Care", "Medical Knowledge", "Communication", "Critical Thinking"], [["step" => 1, "title" => "B.Sc Nursing", "desc" => "4-year nursing degree"], ["step" => 2, "title" => "Registration", "desc" => "Register with State Nursing Council"], ["step" => 3, "title" => "Clinical Experience", "desc" => "Hospital rotations"], ["step" => 4, "title" => "Specialization", "desc" => "ICU, pediatrics, or emergency"], ["step" => 5, "title" => "Growth", "desc" => "Senior nurse, nursing supervisor"]], "B.Sc Nursing", ["nursing", "patient", "hospital", "care"]],

    ["Research Scientist", "science", "science", "Conduct scientific research to advance knowledge in physics, chemistry, or biology.", "₹5,00,000 - ₹15,00,000", "Moderate", ["Research Methodology", "Lab Techniques", "Data Analysis", "Publication"], [["step" => 1, "title" => "B.Sc", "desc" => "Bachelor's in Science discipline"], ["step" => 2, "title" => "M.Sc", "desc" => "Master's with research focus"], ["step" => 3, "title" => "PhD", "desc" => "Doctoral research"], ["step" => 4, "title" => "Postdoc", "desc" => "Postdoctoral fellowship"], ["step" => 5, "title" => "Faculty/Lab", "desc" => "University or research lab position"]], "PhD in Science", ["research", "scientist", "lab", "experiment"]],

    ["AI/ML Engineer", "technology", "science", "Build intelligent systems using artificial intelligence and machine learning.", "₹8,00,000 - ₹30,00,000", "Very High", ["Python", "TensorFlow", "Deep Learning", "Mathematics"], [["step" => 1, "title" => "Education", "desc" => "B.Tech in CS/AI/ML"], ["step" => 2, "title" => "Mathematics", "desc" => "Strong linear algebra, probability"], ["step" => 3, "title" => "ML Frameworks", "desc" => "TensorFlow, PyTorch mastery"], ["step" => 4, "title" => "Projects", "desc" => "Build AI applications, publish research"], ["step" => 5, "title" => "Industry", "desc" => "AI engineer at tech companies"]], "B.Tech/M.Tech in CS/AI", ["artificial intelligence", "machine learning", "deep learning", "neural"]],

    // ==================== COMMERCE STREAM ====================
    ["Chartered Accountant", "business", "commerce", "Handle financial accounting, auditing, taxation, and advisory for businesses.", "₹7,00,000 - ₹25,00,000", "High", ["Accounting", "Taxation", "Auditing", "Financial Analysis"], [["step" => 1, "title" => "Foundation", "desc" => "CA Foundation after 12th Commerce"], ["step" => 2, "title" => "CA Inter", "desc" => "Clear CA Intermediate exams"], ["step" => 3, "title" => "Articleship", "desc" => "3 years practical training"], ["step" => 4, "title" => "CA Final", "desc" => "Clear CA Final exams"], ["step" => 5, "title" => "Practice", "desc" => "Start practice or join a firm"]], "CA Qualification", ["accounting", "tax", "audit", "finance"]],

    ["Company Secretary", "business", "commerce", "Ensure corporate governance, compliance, and legal advisory for companies.", "₹5,00,000 - ₹15,00,000", "Moderate", ["Corporate Law", "Compliance", "Governance", "Legal Drafting"], [["step" => 1, "title" => "CSEET", "desc" => "Clear CS Executive Entrance Test"], ["step" => 2, "title" => "CS Executive", "desc" => "Pass Executive programme"], ["step" => 3, "title" => "CS Professional", "desc" => "Pass Professional programme"], ["step" => 4, "title" => "Training", "desc" => "15 months practical training"], ["step" => 5, "title" => "Practice", "desc" => "Employment or own practice"]], "CS Qualification", ["corporate", "governance", "compliance", "legal"]],

    ["Investment Banker", "business", "commerce", "Advise companies on mergers, acquisitions, and capital raising.", "₹10,00,000 - ₹50,00,000", "High", ["Financial Modeling", "Valuation", "M&A", "Excel"], [["step" => 1, "title" => "Education", "desc" => "B.Com/BBA + MBA Finance"], ["step" => 2, "title" => "Skills", "desc" => "Master financial modeling, valuation"], ["step" => 3, "title" => "CFA", "desc" => "Pursue CFA certification"], ["step" => 4, "title" => "Internship", "desc" => "Investment bank internship"], ["step" => 5, "title" => "Career", "desc" => "Analyst to Associate to VP track"]], "MBA Finance + CFA", ["banking", "investment", "M&A", "stocks"]],

    ["Cost Accountant (CMA)", "business", "commerce", "Manage cost accounting, budgeting, and financial planning for organizations.", "₹5,00,000 - ₹15,00,000", "Moderate", ["Cost Accounting", "Budgeting", "Financial Planning", "Management Accounting"], [["step" => 1, "title" => "Foundation", "desc" => "CMA Foundation after 12th"], ["step" => 2, "title" => "Intermediate", "desc" => "CMA Intermediate exams"], ["step" => 3, "title" => "Final", "desc" => "CMA Final exams"], ["step" => 4, "title" => "Training", "desc" => "Practical training period"], ["step" => 5, "title" => "Practice", "desc" => "Industry or consultancy"]], "CMA Qualification", ["cost", "budget", "management accounting", "planning"]],

    ["Financial Analyst", "business", "commerce", "Analyze financial data to guide business investment decisions.", "₹5,00,000 - ₹18,00,000", "Moderate", ["Financial Modeling", "Excel", "Data Analysis", "Forecasting"], [["step" => 1, "title" => "Education", "desc" => "B.Com/BBA in Finance"], ["step" => 2, "title" => "Technical Skills", "desc" => "Excel, financial modeling, Bloomberg"], ["step" => 3, "title" => "Certifications", "desc" => "CFA or FRM credentials"], ["step" => 4, "title" => "Internships", "desc" => "Banks or investment firms"], ["step" => 5, "title" => "Growth", "desc" => "Senior analyst to portfolio manager"]], "B.Com/MBA Finance", ["finance", "analysis", "stocks", "investment"]],

    ["Digital Marketing Manager", "business", "commerce", "Develop and execute digital marketing strategies for brand growth.", "₹4,00,000 - ₹16,00,000", "High", ["SEO", "Content Strategy", "Analytics", "Social Media"], [["step" => 1, "title" => "Education", "desc" => "BBA/B.Com + Digital Marketing certification"], ["step" => 2, "title" => "Digital Skills", "desc" => "SEO, SEM, social media marketing"], ["step" => 3, "title" => "Analytics", "desc" => "Google Analytics, Facebook Ads"], ["step" => 4, "title" => "Entry Role", "desc" => "Marketing executive or coordinator"], ["step" => 5, "title" => "Management", "desc" => "Marketing manager or head"]], "BBA/B.Com + Certifications", ["marketing", "social media", "SEO", "advertising"]],

    ["E-Commerce Manager", "business", "commerce", "Manage online retail operations, strategy, and growth.", "₹5,00,000 - ₹18,00,000", "High", ["E-Commerce Platforms", "Analytics", "Supply Chain", "Marketing"], [["step" => 1, "title" => "Education", "desc" => "BBA/B.Com or MBA"], ["step" => 2, "title" => "Platform Knowledge", "desc" => "Shopify, Amazon, Flipkart seller tools"], ["step" => 3, "title" => "Marketing", "desc" => "Digital marketing and SEO"], ["step" => 4, "title" => "Entry Role", "desc" => "E-commerce executive"], ["step" => 5, "title" => "Growth", "desc" => "E-commerce head or own store"]], "BBA/MBA", ["ecommerce", "online", "retail", "amazon"]],

    ["Actuary", "business", "commerce", "Use mathematics and statistics to assess financial risk in insurance and finance.", "₹8,00,000 - ₹30,00,000", "High", ["Statistics", "Probability", "Financial Mathematics", "Risk Modeling"], [["step" => 1, "title" => "Education", "desc" => "B.Sc Math/Stats or B.Com"], ["step" => 2, "title" => "Actuarial Exams", "desc" => "Clear IAI or IFoA exams"], ["step" => 3, "title" => "Internship", "desc" => "Insurance or consulting firm"], ["step" => 4, "title" => "Fellowship", "desc" => "Complete all actuarial papers"], ["step" => 5, "title" => "Career", "desc" => "Chief actuary or risk consultant"]], "Actuarial Fellowship", ["actuary", "risk", "insurance", "statistics"]],

    ["Human Resources Manager", "business", "commerce", "Manage recruitment, employee relations, training, and organizational development.", "₹4,00,000 - ₹15,00,000", "Moderate", ["Recruitment", "Employee Relations", "HR Policies", "Training"], [["step" => 1, "title" => "Education", "desc" => "BBA/B.Com + MBA in HR"], ["step" => 2, "title" => "Skills", "desc" => "Labor laws, HRMS tools"], ["step" => 3, "title" => "Entry Role", "desc" => "HR executive or recruiter"], ["step" => 4, "title" => "Certifications", "desc" => "SHRM or CIPD certifications"], ["step" => 5, "title" => "Growth", "desc" => "HR manager to CHRO"]], "MBA in HR", ["HR", "recruitment", "people", "management"]],

    ["Supply Chain Manager", "business", "commerce", "Oversee logistics, procurement, and distribution operations.", "₹5,00,000 - ₹18,00,000", "High", ["Logistics", "Procurement", "Inventory Management", "ERP"], [["step" => 1, "title" => "Education", "desc" => "BBA/B.Com + MBA in Operations"], ["step" => 2, "title" => "Skills", "desc" => "ERP systems, SAP, logistics planning"], ["step" => 3, "title" => "Entry Role", "desc" => "Supply chain executive"], ["step" => 4, "title" => "Certifications", "desc" => "CSCP or CPSM certification"], ["step" => 5, "title" => "Growth", "desc" => "Supply chain director"]], "MBA in Operations", ["logistics", "supply chain", "procurement", "inventory"]],

    // ==================== ARTS / HUMANITIES STREAM ====================
    ["Lawyer / Advocate", "law", "arts", "Represent clients in legal matters, draft legal documents, and argue cases in court.", "₹4,00,000 - ₹20,00,000", "Moderate", ["Legal Research", "Argumentation", "Drafting", "Constitutional Law"], [["step" => 1, "title" => "Law Degree", "desc" => "5-year BA LLB or 3-year LLB"], ["step" => 2, "title" => "Bar Council", "desc" => "Enroll with Bar Council of India"], ["step" => 3, "title" => "Apprenticeship", "desc" => "Practice under senior advocate"], ["step" => 4, "title" => "Specialization", "desc" => "Criminal, corporate, or civil law"], ["step" => 5, "title" => "Practice", "desc" => "Independent practice or law firm"]], "BA LLB / LLB", ["law", "legal", "court", "advocate", "justice"]],

    ["Journalist", "creative", "arts", "Report news, investigate stories, and present information to the public.", "₹3,00,000 - ₹12,00,000", "Moderate", ["Writing", "Research", "Interviewing", "Media Ethics"], [["step" => 1, "title" => "Education", "desc" => "BA in Journalism or Mass Communication"], ["step" => 2, "title" => "Internship", "desc" => "Newspaper, TV, or digital media"], ["step" => 3, "title" => "Portfolio", "desc" => "Build published work portfolio"], ["step" => 4, "title" => "Entry Role", "desc" => "Reporter or sub-editor"], ["step" => 5, "title" => "Growth", "desc" => "Senior journalist, editor, anchor"]], "BA in Journalism", ["news", "media", "writing", "reporting"]],

    ["Psychologist", "healthcare", "arts", "Study human behavior and mental processes, provide counseling and therapy.", "₹3,00,000 - ₹12,00,000", "High", ["Counseling", "Assessment", "Research", "Empathy"], [["step" => 1, "title" => "BA Psychology", "desc" => "Bachelor's in Psychology"], ["step" => 2, "title" => "MA Psychology", "desc" => "Master's with clinical focus"], ["step" => 3, "title" => "M.Phil/PhD", "desc" => "RCI registration for clinical practice"], ["step" => 4, "title" => "Internship", "desc" => "Clinical internship hours"], ["step" => 5, "title" => "Practice", "desc" => "Hospital, school, or private practice"]], "MA/M.Phil in Psychology", ["psychology", "mental health", "counseling", "therapy"]],

    ["Sociologist", "science", "arts", "Study society, social behavior, and cultural patterns through research.", "₹3,00,000 - ₹10,00,000", "Moderate", ["Research", "Data Analysis", "Critical Thinking", "Writing"], [["step" => 1, "title" => "BA Sociology", "desc" => "Bachelor's in Sociology"], ["step" => 2, "title" => "MA Sociology", "desc" => "Master's degree"], ["step" => 3, "title" => "Research", "desc" => "Fieldwork and publications"], ["step" => 4, "title" => "PhD", "desc" => "Doctoral research"], ["step" => 5, "title" => "Career", "desc" => "Academia, NGOs, policy research"]], "MA/PhD in Sociology", ["society", "research", "culture", "social"]],

    ["UX/UI Designer", "creative", "arts", "Create intuitive and visually appealing user interfaces and experiences.", "₹5,00,000 - ₹20,00,000", "High", ["Figma", "User Research", "Prototyping", "Visual Design"], [["step" => 1, "title" => "Fundamentals", "desc" => "Design principles, color theory, typography"], ["step" => 2, "title" => "Tools", "desc" => "Master Figma, Adobe XD, Sketch"], ["step" => 3, "title" => "Portfolio", "desc" => "Case studies with design process"], ["step" => 4, "title" => "User Research", "desc" => "Usability testing, data-driven design"], ["step" => 5, "title" => "Career", "desc" => "Junior to senior UX/UI designer"]], "BDes/Self-taught", ["design", "UI", "UX", "user experience", "interface"]],

    ["Graphic Designer", "creative", "arts", "Create visual content for brands, marketing, and digital media.", "₹3,00,000 - ₹12,00,000", "Moderate", ["Adobe Creative Suite", "Typography", "Branding", "Layout Design"], [["step" => 1, "title" => "Education", "desc" => "BDes or self-taught online courses"], ["step" => 2, "title" => "Software", "desc" => "Photoshop, Illustrator, InDesign, Figma"], ["step" => 3, "title" => "Portfolio", "desc" => "Diverse design projects portfolio"], ["step" => 4, "title" => "Freelance/Agency", "desc" => "Gain client experience"], ["step" => 5, "title" => "Specialize", "desc" => "Branding, web design, or motion graphics"]], "BDes or Diploma", ["graphic", "design", "visual", "branding"]],

    ["Content Writer", "creative", "arts", "Create engaging written content for websites, blogs, and marketing.", "₹2,50,000 - ₹10,00,000", "High", ["Writing", "SEO", "Research", "Editing"], [["step" => 1, "title" => "Writing Skills", "desc" => "Practice and formal education"], ["step" => 2, "title" => "Niche", "desc" => "Technical, marketing, or creative writing"], ["step" => 3, "title" => "Portfolio", "desc" => "Blog, guest posts, published work"], ["step" => 4, "title" => "SEO", "desc" => "Learn SEO and content optimization"], ["step" => 5, "title" => "Growth", "desc" => "Content strategist or editor"]], "BA English/Journalism", ["writing", "content", "blog", "SEO", "copywriting"]],

    ["High School Teacher", "education", "arts", "Educate and mentor students in specific subject areas.", "₹3,00,000 - ₹8,00,000", "Stable", ["Subject Expertise", "Classroom Management", "Communication", "Patience"], [["step" => 1, "title" => "Bachelor's", "desc" => "BA/B.Sc in your subject"], ["step" => 2, "title" => "B.Ed", "desc" => "Bachelor of Education degree"], ["step" => 3, "title" => "TET/CTET", "desc" => "Clear Teacher Eligibility Test"], ["step" => 4, "title" => "Teaching", "desc" => "Apply to schools"], ["step" => 5, "title" => "Growth", "desc" => "Senior teacher, HOD, or principal"]], "BA/B.Sc + B.Ed", ["teaching", "education", "school", "students"]],

    ["Political Scientist", "government", "arts", "Analyze political systems, policies, and government structures.", "₹4,00,000 - ₹12,00,000", "Moderate", ["Political Theory", "Research", "Policy Analysis", "Public Administration"], [["step" => 1, "title" => "BA Political Science", "desc" => "Bachelor's degree"], ["step" => 2, "title" => "MA", "desc" => "Master's in Political Science"], ["step" => 3, "title" => "Research", "desc" => "Think tanks, policy institutes"], ["step" => 4, "title" => "PhD", "desc" => "Optional for academia"], ["step" => 5, "title" => "Career", "desc" => "Policy advisor, academic, analyst"]], "MA/PhD in Political Science", ["politics", "government", "policy", "democracy"]],

    ["Social Worker", "healthcare", "arts", "Help individuals and communities overcome social challenges and access services.", "₹2,50,000 - ₹8,00,000", "High", ["Counseling", "Community Work", "Advocacy", "Empathy"], [["step" => 1, "title" => "BSW", "desc" => "Bachelor of Social Work"], ["step" => 2, "title" => "MSW", "desc" => "Master of Social Work"], ["step" => 3, "title" => "Fieldwork", "desc" => "NGO and community internships"], ["step" => 4, "title" => "Specialize", "desc" => "Child welfare, healthcare, or community"], ["step" => 5, "title" => "Career", "desc" => "NGO, government, or hospital social worker"]], "BSW/MSW", ["social", "community", "welfare", "NGO"]],

    ["Historian", "education", "arts", "Research, analyze, and interpret historical events and documents.", "₹3,00,000 - ₹10,00,000", "Moderate", ["Research", "Archival Work", "Writing", "Critical Analysis"], [["step" => 1, "title" => "BA History", "desc" => "Bachelor's in History"], ["step" => 2, "title" => "MA History", "desc" => "Master's with specialization"], ["step" => 3, "title" => "PhD", "desc" => "Doctoral research"], ["step" => 4, "title" => "Publications", "desc" => "Research papers and books"], ["step" => 5, "title" => "Career", "desc" => "Professor, museum curator, archivist"]], "MA/PhD in History", ["history", "heritage", "museum", "archaeology"]],

    ["Foreign Language Expert", "education", "arts", "Translate, interpret, and teach foreign languages for business and diplomacy.", "₹3,00,000 - ₹15,00,000", "High", ["Language Proficiency", "Translation", "Cultural Knowledge", "Teaching"], [["step" => 1, "title" => "Education", "desc" => "BA in Foreign Language or Literature"], ["step" => 2, "title" => "Certification", "desc" => "DELF/DELE/JLPT language certifications"], ["step" => 3, "title" => "Immersion", "desc" => "Study abroad or immersion programs"], ["step" => 4, "title" => "Entry Role", "desc" => "Translator, interpreter, or teacher"], ["step" => 5, "title" => "Growth", "desc" => "Embassy, MNC, or UN interpreter"]], "BA in Foreign Language", ["language", "translation", "interpreter", "foreign"]],

    // ==================== DESIGN / CREATIVE STREAM ====================
    ["Architect", "creative", "design", "Design buildings, spaces, and structures balancing aesthetics and functionality.", "₹4,00,000 - ₹18,00,000", "Moderate", ["AutoCAD", "3D Modeling", "Sustainability", "Structural Knowledge"], [["step" => 1, "title" => "B.Arch", "desc" => "5-year Bachelor of Architecture (NATA exam)"], ["step" => 2, "title" => "Software", "desc" => "AutoCAD, Revit, SketchUp, 3ds Max"], ["step" => 3, "title" => "Internship", "desc" => "Architecture firm internship"], ["step" => 4, "title" => "Registration", "desc" => "Register with Council of Architecture"], ["step" => 5, "title" => "Practice", "desc" => "Junior architect to own firm"]], "B.Arch", ["architecture", "building", "design", "structure"]],

    ["Interior Designer", "creative", "design", "Design functional and aesthetic interior spaces for homes and offices.", "₹3,00,000 - ₹15,00,000", "High", ["Space Planning", "3D Visualization", "Color Theory", "Material Knowledge"], [["step" => 1, "title" => "Education", "desc" => "B.Sc/Diploma in Interior Design"], ["step" => 2, "title" => "Software", "desc" => "AutoCAD, SketchUp, V-Ray"], ["step" => 3, "title" => "Portfolio", "desc" => "Build diverse design portfolio"], ["step" => 4, "title" => "Internship", "desc" => "Work with interior design firms"], ["step" => 5, "title" => "Career", "desc" => "Senior designer or own studio"]], "B.Sc/Diploma in Interior Design", ["interior", "decor", "space", "furniture"]],

    ["Fashion Designer", "creative", "design", "Design clothing, accessories, and fashion collections.", "₹3,00,000 - ₹18,00,000", "Moderate", ["Fashion Illustration", "Textile Knowledge", "Pattern Making", "Trend Analysis"], [["step" => 1, "title" => "Education", "desc" => "B.Des in Fashion Design (NIFT/NID exam)"], ["step" => 2, "title" => "Skills", "desc" => "Illustration, draping, pattern making"], ["step" => 3, "title" => "Internship", "desc" => "Fashion house or brand internship"], ["step" => 4, "title" => "Portfolio", "desc" => "Create original collections"], ["step" => 5, "title" => "Career", "desc" => "Brand designer or own label"]], "B.Des in Fashion", ["fashion", "clothing", "textile", "style"]],

    ["Film Director", "creative", "design", "Direct films, manage creative vision, and guide actors and crew.", "₹3,00,000 - ₹50,00,000", "Variable", ["Storytelling", "Visual Composition", "Leadership", "Editing"], [["step" => 1, "title" => "Education", "desc" => "Film school (FTII, Whistling Woods) or self-taught"], ["step" => 2, "title" => "Short Films", "desc" => "Create short films and documentaries"], ["step" => 3, "title" => "Assistant Director", "desc" => "Work as AD on film sets"], ["step" => 4, "title" => "Networking", "desc" => "Build industry connections"], ["step" => 5, "title" => "Feature Film", "desc" => "Direct independent or commercial features"]], "Film School Diploma", ["film", "cinema", "movies", "directing"]],

    ["Animator", "creative", "design", "Create animated content for films, games, advertising, and digital media.", "₹3,00,000 - ₹15,00,000", "High", ["2D/3D Animation", "Maya", "After Effects", "Storytelling"], [["step" => 1, "title" => "Education", "desc" => "B.Sc/Diploma in Animation"], ["step" => 2, "title" => "Software", "desc" => "Maya, Blender, After Effects"], ["step" => 3, "title" => "Portfolio", "desc" => "Showreel of animations"], ["step" => 4, "title" => "Entry Role", "desc" => "Junior animator at studio"], ["step" => 5, "title" => "Growth", "desc" => "Lead animator or VFX artist"]], "B.Sc/Diploma in Animation", ["animation", "3D", "cartoon", "VFX", "motion"]],

    ["Product Designer", "creative", "design", "Design physical or digital products from concept to market-ready form.", "₹5,00,000 - ₹20,00,000", "High", ["Industrial Design", "Prototyping", "User Research", "CAD"], [["step" => 1, "title" => "Education", "desc" => "B.Des in Product/Industrial Design"], ["step" => 2, "title" => "Skills", "desc" => "CAD, prototyping, user research"], ["step" => 3, "title" => "Internship", "desc" => "Design consultancy or product company"], ["step" => 4, "title" => "Portfolio", "desc" => "End-to-end product case studies"], ["step" => 5, "title" => "Career", "desc" => "Product designer at tech or consumer company"]], "B.Des in Product Design", ["product", "industrial", "prototype", "innovation"]],

    // ==================== GOVERNMENT / PUBLIC SERVICE ====================
    ["IAS Officer", "government", "any", "Serve as a civil servant in Indian Administrative Service managing districts and policy.", "₹8,00,000 - ₹20,00,000", "Stable", ["Public Administration", "Policy Making", "Leadership", "Communication"], [["step" => 1, "title" => "Graduation", "desc" => "Any bachelor's degree"], ["step" => 2, "title" => "UPSC Prep", "desc" => "12-18 months dedicated preparation"], ["step" => 3, "title" => "Prelims", "desc" => "Clear UPSC Preliminary exam"], ["step" => 4, "title" => "Mains + Interview", "desc" => "Clear Mains and personality test"], ["step" => 5, "title" => "Training", "desc" => "LBSNAA training, district posting"]], "Any Graduation + UPSC", ["IAS", "civil services", "UPSC", "government", "officer"]],

    ["IPS Officer", "government", "any", "Lead law enforcement operations as Indian Police Service officer.", "₹7,00,000 - ₹18,00,000", "Stable", ["Law Enforcement", "Leadership", "Physical Fitness", "Decision Making"], [["step" => 1, "title" => "Graduation", "desc" => "Any bachelor's degree"], ["step" => 2, "title" => "UPSC Prep", "desc" => "Focus on General Studies + Optional"], ["step" => 3, "title" => "UPSC Exam", "desc" => "Clear Prelims, Mains, Interview"], ["step" => 4, "title" => "Training", "desc" => "SVPNPA Hyderabad training"], ["step" => 5, "title" => "Posting", "desc" => "ASP to SP to DIG progression"]], "Any Graduation + UPSC", ["IPS", "police", "law enforcement", "UPSC"]],

    ["Bank PO", "government", "commerce", "Manage banking operations as Probationary Officer in public sector banks.", "₹5,00,000 - ₹12,00,000", "Stable", ["Banking Knowledge", "Financial Analysis", "Customer Service", "Management"], [["step" => 1, "title" => "Graduation", "desc" => "Any bachelor's degree"], ["step" => 2, "title" => "IBPS/SBI Prep", "desc" => "Prepare for bank PO exams"], ["step" => 3, "title" => "Prelims + Mains", "desc" => "Clear written exams"], ["step" => 4, "title" => "Interview", "desc" => "Personal interview round"], ["step" => 5, "title" => "Training", "desc" => "Probation period, branch posting"]], "Any Graduation", ["banking", "bank PO", "IBPS", "SBI", "finance"]],

    ["Defense Officer", "government", "any", "Serve in Indian Armed Forces (Army, Navy, Air Force) as commissioned officer.", "₹8,00,000 - ₹20,00,000", "Stable", ["Leadership", "Physical Fitness", "Strategy", "Discipline"], [["step" => 1, "title" => "Education", "desc" => "12th/Graduation depending on entry"], ["step" => 2, "title" => "Entrance Exam", "desc" => "NDA/CDS/AFCAT exam"], ["step" => 3, "title" => "SSB Interview", "desc" => "5-day SSB selection process"], ["step" => 4, "title" => "Training", "desc" => "IMA/OTA/AFA/INA training"], ["step" => 5, "title" => "Commission", "desc" => "Commissioned officer posting"]], "Graduation + NDA/CDS", ["army", "navy", "airforce", "defense", "military"]],

    // ==================== MORE SCIENCE/TECHNOLOGY ====================
    ["Cloud Architect", "technology", "science", "Design and manage cloud computing infrastructure and solutions.", "₹12,00,000 - ₹35,00,000", "Very High", ["AWS", "Azure", "DevOps", "Microservices"], [["step" => 1, "title" => "Education", "desc" => "B.Tech in CS/IT"], ["step" => 2, "title" => "Cloud Skills", "desc" => "Master AWS, Azure, or GCP"], ["step" => 3, "title" => "Certifications", "desc" => "AWS Solutions Architect, Azure certs"], ["step" => 4, "title" => "Experience", "desc" => "Cloud engineer roles"], ["step" => 5, "title" => "Architect", "desc" => "Senior cloud architect position"]], "B.Tech + Cloud Certs", ["cloud", "AWS", "Azure", "DevOps", "infrastructure"]],

    ["Product Manager", "business", "science", "Lead product development from conception to launch and growth.", "₹10,00,000 - ₹30,00,000", "High", ["Product Strategy", "Agile", "User Research", "Analytics"], [["step" => 1, "title" => "Education", "desc" => "B.Tech/MBA combination preferred"], ["step" => 2, "title" => "Technical Understanding", "desc" => "Software development, UX, analytics"], ["step" => 3, "title" => "Entry Role", "desc" => "Associate PM or business analyst"], ["step" => 4, "title" => "Skills", "desc" => "Roadmapping, prioritization, agile"], ["step" => 5, "title" => "Growth", "desc" => "Senior PM to VP Product"]], "B.Tech/MBA", ["product", "management", "agile", "roadmap"]],

    ["Dentist", "healthcare", "science", "Diagnose and treat oral health issues, perform dental procedures.", "₹5,00,000 - ₹20,00,000", "Stable", ["Dental Surgery", "Patient Care", "Diagnosis", "Manual Dexterity"], [["step" => 1, "title" => "NEET", "desc" => "Clear NEET-UG exam"], ["step" => 2, "title" => "BDS", "desc" => "5-year Bachelor of Dental Surgery"], ["step" => 3, "title" => "Internship", "desc" => "1-year compulsory internship"], ["step" => 4, "title" => "MDS", "desc" => "Optional Master's specialization"], ["step" => 5, "title" => "Practice", "desc" => "Hospital or private clinic"]], "BDS / MDS", ["dental", "teeth", "oral", "dentist"]],

    ["Veterinarian", "healthcare", "science", "Diagnose and treat animal diseases, provide preventive healthcare.", "₹4,00,000 - ₹12,00,000", "Moderate", ["Animal Science", "Surgery", "Diagnosis", "Compassion"], [["step" => 1, "title" => "Entrance", "desc" => "NEET or state veterinary entrance"], ["step" => 2, "title" => "B.V.Sc", "desc" => "5-year veterinary degree"], ["step" => 3, "title" => "Internship", "desc" => "Clinical training with animals"], ["step" => 4, "title" => "Specialization", "desc" => "Surgery, medicine, or pathology"], ["step" => 5, "title" => "Practice", "desc" => "Government, private clinic, or research"]], "B.V.Sc & AH", ["veterinary", "animals", "pets", "vet"]],

    ["Environmental Scientist", "science", "science", "Study environmental problems and develop solutions for sustainability.", "₹4,00,000 - ₹12,00,000", "High", ["Environmental Science", "Data Analysis", "GIS", "Policy"], [["step" => 1, "title" => "Education", "desc" => "B.Sc/B.Tech in Environmental Science"], ["step" => 2, "title" => "Master's", "desc" => "M.Sc/M.Tech in Environmental Engineering"], ["step" => 3, "title" => "Skills", "desc" => "GIS, remote sensing, EIA"], ["step" => 4, "title" => "Experience", "desc" => "NGOs, government agencies, consulting"], ["step" => 5, "title" => "Career", "desc" => "Environmental consultant or researcher"]], "M.Sc/M.Tech", ["environment", "sustainability", "pollution", "climate"]],

    ["Physiotherapist", "healthcare", "science", "Help patients recover from injuries and improve mobility.", "₹3,00,000 - ₹10,00,000", "High", ["Anatomy", "Rehabilitation", "Exercise Prescription", "Patient Assessment"], [["step" => 1, "title" => "BPT", "desc" => "4-year Bachelor of Physiotherapy"], ["step" => 2, "title" => "Internship", "desc" => "6-month clinical internship"], ["step" => 3, "title" => "MPT", "desc" => "Optional Master's for specialization"], ["step" => 4, "title" => "Practice", "desc" => "Hospital, sports clinic, or private"], ["step" => 5, "title" => "Specialize", "desc" => "Sports, neuro, or orthopedic physio"]], "BPT / MPT", ["physiotherapy", "rehabilitation", "exercise", "mobility"]],

    // ==================== ADDITIONAL CAREERS ====================
    ["Event Manager", "business", "arts", "Plan, organize, and execute events from corporate conferences to weddings.", "₹3,00,000 - ₹15,00,000", "High", ["Event Planning", "Vendor Management", "Budgeting", "Creativity"], [["step" => 1, "title" => "Education", "desc" => "BBA/BA or Event Management diploma"], ["step" => 2, "title" => "Internship", "desc" => "Event management company"], ["step" => 3, "title" => "Coordination", "desc" => "Start as event coordinator"], ["step" => 4, "title" => "Portfolio", "desc" => "Build a portfolio of managed events"], ["step" => 5, "title" => "Growth", "desc" => "Event director or own company"]], "BBA/Diploma", ["events", "wedding", "conference", "planning"]],

    ["Hotel Manager", "business", "commerce", "Manage hotel operations, staff, guest services, and revenue.", "₹4,00,000 - ₹15,00,000", "Moderate", ["Hospitality", "Staff Management", "Customer Service", "Revenue Management"], [["step" => 1, "title" => "Education", "desc" => "BHM (Bachelor of Hotel Management)"], ["step" => 2, "title" => "Internship", "desc" => "Luxury hotel operational training"], ["step" => 3, "title" => "Entry Role", "desc" => "Front desk or F&B supervisor"], ["step" => 4, "title" => "Departments", "desc" => "Rotate across hotel departments"], ["step" => 5, "title" => "Management", "desc" => "Assistant GM to General Manager"]], "BHM", ["hotel", "hospitality", "tourism", "restaurant"]],

    ["Pilot", "technology", "science", "Fly commercial or private aircraft, ensuring passenger safety.", "₹10,00,000 - ₹40,00,000", "Moderate", ["Aviation", "Navigation", "Communication", "Decision Making"], [["step" => 1, "title" => "Education", "desc" => "12th with Physics & Math (min 50%)"], ["step" => 2, "title" => "Flying School", "desc" => "DGCA-approved flying training"], ["step" => 3, "title" => "CPL", "desc" => "Commercial Pilot License (200 hrs)"], ["step" => 4, "title" => "Type Rating", "desc" => "Aircraft-specific type rating"], ["step" => 5, "title" => "Airline Job", "desc" => "First Officer to Captain progression"]], "CPL + Type Rating", ["pilot", "aviation", "flying", "airline", "aircraft"]],

    ["Sports Coach", "education", "any", "Train athletes and teams to improve performance and achieve competitive goals.", "₹3,00,000 - ₹12,00,000", "Moderate", ["Sports Science", "Strategy", "Motivation", "Fitness Training"], [["step" => 1, "title" => "Education", "desc" => "B.P.Ed or B.Sc in Sports Science"], ["step" => 2, "title" => "Playing Experience", "desc" => "Competitive sports background"], ["step" => 3, "title" => "Certification", "desc" => "NIS diploma or coaching license"], ["step" => 4, "title" => "Coaching", "desc" => "School/club level coaching"], ["step" => 5, "title" => "Growth", "desc" => "State/national team or academy coach"]], "B.P.Ed / NIS Diploma", ["sports", "coaching", "fitness", "athlete", "training"]],

    ["Ethical Hacker", "technology", "science", "Test security systems by finding vulnerabilities before malicious hackers do.", "₹5,00,000 - ₹20,00,000", "Very High", ["Penetration Testing", "Network Security", "Kali Linux", "Scripting"], [["step" => 1, "title" => "Education", "desc" => "B.Tech in CS/IT or self-taught"], ["step" => 2, "title" => "Skills", "desc" => "Networking, Linux, scripting"], ["step" => 3, "title" => "Certifications", "desc" => "CEH, OSCP, CompTIA PenTest+"], ["step" => 4, "title" => "Practice", "desc" => "Bug bounties, CTF competitions"], ["step" => 5, "title" => "Career", "desc" => "Security consultant or red team lead"]], "B.Tech + CEH/OSCP", ["hacking", "security", "penetration", "vulnerability"]],

    ["Statistician", "science", "science", "Apply statistical methods to collect, analyze, and interpret data.", "₹5,00,000 - ₹18,00,000", "High", ["Statistics", "R", "Python", "Probability Theory"], [["step" => 1, "title" => "Education", "desc" => "B.Sc/M.Sc in Statistics or Math"], ["step" => 2, "title" => "Tools", "desc" => "R, Python, SPSS, SAS"], ["step" => 3, "title" => "ISS Exam", "desc" => "Optional Indian Statistical Service"], ["step" => 4, "title" => "Experience", "desc" => "Industry, government, or academia"], ["step" => 5, "title" => "Growth", "desc" => "Senior statistician or data lead"]], "M.Sc in Statistics", ["statistics", "data", "probability", "analysis"]],

    ["Chartered Financial Planner", "business", "commerce", "Create comprehensive financial plans for individuals and families.", "₹5,00,000 - ₹20,00,000", "High", ["Financial Planning", "Investment", "Tax Planning", "Insurance"], [["step" => 1, "title" => "Education", "desc" => "B.Com/BBA + CFP certification"], ["step" => 2, "title" => "CFP Exam", "desc" => "Clear FPSB India CFP exams"], ["step" => 3, "title" => "Experience", "desc" => "Work at financial advisory firm"], ["step" => 4, "title" => "Client Base", "desc" => "Build client relationships"], ["step" => 5, "title" => "Growth", "desc" => "Independent financial planner"]], "B.Com + CFP", ["financial planning", "investment", "wealth", "insurance"]]
];

// Track results
$inserted = 0;
$errors = [];

try {
    // Check if careers already exist
    $check = $db->query("SELECT COUNT(*) FROM careers");
    $existing = $check->fetchColumn();

    if ($existing > 0) {
        echo json_encode([
            "success" => false,
            "message" => "Careers table already has $existing entries. Clear the table first if you want to re-seed.",
            "existing_count" => (int) $existing
        ]);
        exit;
    }

    $stmt = $db->prepare("INSERT INTO careers (title, category, stream, description, salary_range, growth, skills, roadmap, education_required, match_keywords) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

    foreach ($careers as $c) {
        try {
            $stmt->execute([
                $c[0],  // title
                $c[1],  // category
                $c[2],  // stream
                $c[3],  // description
                $c[4],  // salary_range
                $c[5],  // growth
                json_encode($c[6]),  // skills
                json_encode($c[7]),  // roadmap
                $c[8],  // education_required
                json_encode($c[9])   // match_keywords
            ]);
            $inserted++;
        } catch (PDOException $e) {
            $errors[] = "Failed to insert '{$c[0]}': " . $e->getMessage();
        }
    }

    header('Content-Type: application/json');
    echo json_encode([
        "success" => true,
        "message" => "Seeded $inserted careers successfully!",
        "inserted" => $inserted,
        "total_attempted" => count($careers),
        "errors" => $errors
    ], JSON_PRETTY_PRINT);

} catch (PDOException $e) {
    header('Content-Type: application/json');
    echo json_encode([
        "success" => false,
        "message" => "Seeding failed: " . $e->getMessage()
    ]);
}
?>